baseURL = 'https://blog.beatrevival.me'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
title = 'Beat Revival Blog'

[params]
  goToTop = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/BeatRevivalMEC"

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/beatrevival.me"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Beat-Revival"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/FGftmuRrrG"

[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content/"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
  pageRef="/"
  name="Home"
  url="/"
  weight = 10
  [[Languages.en-us.menu.main]]
  pageRef="posts"
  name="Posts"
  url="/posts/"
  weight = 20